public enum TypeTravail {
    ROUTIER,
    GAZ_ELECTRIQUE,
    CONSTRUCTION_RENOVATION,
    ENTRETIEN_PAYSAGER,
    TRANSPORT_COMMUN,
    SIGNALISATION_ECLAIRAGE,
    SOUTERRAINS,
    RESIDENTIEL,
    ENTRETIEN_URBAIN,
    ENTRETIEN_RESEAU_TELECOMMUNICATION
}
